language: python
python:
- '3.5'
sudo: required
notifications:
  email:
    recipients: sbadillo@gmail.com
    on_success: never
    on_failure: always
branches:
  only:
  - sources

env:
  global:
    secure: "n4VG1mH0lSbsiJg4pkVVBhLpdTK61cB9BSpunZnv6VHjGMvxZGjw+wTr1ZaH9uYG+utWowDWC7FLtd6u/1lvQ/fU/HaNGU6TIWoUbQugWIu/t07WO2zDgbfrvyoRfBpf1jn6yX3QVPWNQCd8mAIFx/7fqhaWArisivQt9mOp7PXMorR1V7TGUb/qZ6rTg1KmJgjD8xzJj2wLqIJTd+K2liMfw289eP9liD+028jA6jPipqyQM4a/Oe2Z6O2erte3kFJTPoQJlFqIm3jaVAXddMFpgTbzR+yr9VAJcOY93Vy/my2HXxyjtFjjF6idVEZHgBow/aW4ahkCkvZvjqcYjYsp2eoi5P12EQd42gcQoM1aSL/fqjHF1dUiF/9/H6Zhmi+28JllRIKb202gAVT/SBTDyGYIPcMSSytR5tromYgVWsxYWtSzRfPv74Ao9XyJbRESxcJ5qyr0glDdl1dmPO+FVKauQc9w2drPFfSo0DANSsQHaw1ctRbzfGTgMgznSKusKf1rn66qjoyncDRy6UC6ZjGH1qi8vB6pRJ3+AjS7H5Aj2tLladux6XOyyepNF0oZ6SHLklgCBGbx79fLO3SenWfkd2ICGP2ijSvzEhKLW9rIwdCCwsYl9qEInWBbJwe7Kv/GhPwHoTlIXMeXBHUdSKl0c/b8TXggWheSciI="

install:
- pip install -r requirements.txt
script:
- make publish github
