language: python
python:
- '3.5'
sudo: required
notifications:
  email:
    recipients: sbadillo@gmail.com
    on_success: never
    on_failure: always
branches:
  only:
  - sources

env:
  global:
    secure: "m8b3YjDUtZzYh7hmrtPRF/jPdxYGAAAP1Aoumn1TsMMWd5Y/rqTV5CWL6ISm4CmfEIpAlvkobBBmVFOAdCN0tA5u8pa1TF/ZViG489JwMiMQnWdSdeXCo+1TGj43F8+gfMwL+oBNYnvJRhQvV11qFs79Mwa0kfLt2NanD2i0MCWRccG1OIxXTm7eykc1Of/kRV14CKlWaXCLnvHkA+hS0XopYg3fRD3mb6JrKJtoPANTigzwWkqHBDVMIO0brnbhCFGX69Lh6LSck5nGMzL6/nTDsGXi5vXIe5M/BnOJDV20bPuoGDG2k+FaUX4Pv8HKaCiCaGiQDCN2l5O6R3iIegCYRVhhaVyxJ7guPgBEHni4SMExEFA/EoMkFkwaV5+tYcDt0VklGRwXwqMvBYSz+jYD6gIYqgDOslF3MZOBItkzgHd96FUdFtcire8uilbzLiecQLooCAOj6dwLblFewMlP4Feesz9Y29R3/Wr0LqmHqgsBOByWtK5P5+04CgZ8RMhpZb917K/ujT4PD8arlh3h2INntOIKNWdvFHzPHZTuxr0RIN9dBAaO2UW/w5Jleoloibxn5+RUcRfNYiBxzHiDFFLrj7yAohVeTAPyN7k1yTm2xkfmOzP4VhkRngHhXH0/5QpsNVQQx2AyCiKmBKaz4OcOE9Eh2/mmc1MIpu0="

install:
- pip install -r requirements.txt
script:
- make publish github
